# create device
POST http://localhost:8000/api/devices
Content-Type: application/json

{
  "userId": "43954c12-552f-4f52-8523-4d38bb8f6389",
  "name": "Device 1",
  "type": "fridge",
  "model": "LA 39995",
  "description": "Cool",
  "serviceInterval": 30,
  "dateLastService": "Fri Oct 19 2018 19:27:28",
  "notifyBeforeService": 20
}

###

# get one device 
GET http://localhost:8000/api/devices/62e1f9b0-b19e-4d56-b388-935ca81fceb6

###

# get device sectors
GET http://localhost:8000/api/devices/8bcea6c3-c7a6-4ea5-9b70-084743801ab2/sectors


#### delete device
DELETE http://localhost:8000/api/devices/96409d57-2594-4b0f-80d0-e8e8ad93dbe5