# create sectors
POST http://localhost:8000/api/sectors
Content-Type: application/json

{
  "deviceId": "8bcea6c3-c7a6-4ea5-9b70-084743801ab2",
  "sectorTrackers": [
    {
      "name": "Sector 1",
      "uuid": "31708d9a-4b3a-415d-9487-7f6e253b6aa1",
      "number": 1,
      "location": "Kitchen",
      "maxTemperature": 150,
      "minTemperature": 10,
      "trackerSetupDate": "Fri Oct 19 2018 19:27:28",
      "maxTimeExcess": 500
    },
    {
      "name": "Sector 2",
      "uuid": "a1192bdf-c2ca-4182-baf6-e817e0f8c9ab",
      "number": 2,
      "location": "Kitchen",
      "maxTemperature": 120,
      "minTemperature": 50,
      "trackerSetupDate": "Fri Oct 11 2018 19:27:28",
      "maxTimeExcess": 240
    }
  ]
}

###

# get one sector
GET http://localhost:8000/api/sectors/4755e587-3600-4f5f-8c08-bd96862cd02f

### get all sectors
GET http://localhost:8000/api/sectors

### set critical situation
POST http://localhost:8000/api/sectors/31708d9a-4b3a-415d-9487-7f6e253b6aa1/critical
Content-Type: application/json

{
  "timeExcess": 233
}

### update last temperatures
PUT http://localhost:8000/api/sectors/temperatures
Content-Type: application/json

{
  "sectorTemperatures": [
    {
      "uuid": "31708d9a-4b3a-415d-9487-7f6e253b6aa1",
      "currentTemp": 200
    },
    {
      "uuid": "a1192bdf-c2ca-4182-baf6-e817e0f8c9ab",
      "currentTemp": 400
    }
  ]
}

### set service
POST http://localhost:8000/api/sectors/a1192bdf-c2ca-4182-baf6-e817e0f8c9ab/service
Content-Type: application/json

{
  "hours": 200,
  "minutes": 17
}




