### get device services
GET http://localhost:8000/api/statistics/c004e5ad-dbb4-4a9a-9025-233988cab670/service

### get sectors statistics
GET http://localhost:8000/api/statistics/c004e5ad-dbb4-4a9a-9025-233988cab670/sectors